name: nutrition_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #packages
#  flutter_native_splash: ^2.3.1
  get_it: ^7.2.0
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  freezed: ^2.3.2
  json_annotation: ^4.8.0
  crypto: ^3.0.2
  font_awesome_flutter: ^10.4.0
  intl: ^0.18.1
  flutter_svg: ^2.0.7
  http: ^1.1.0
  shimmer: ^3.0.0
  super_tooltip: ^2.0.4
  cached_network_image: ^3.2.3
  expandable: ^5.0.1
  flutter_switch: ^0.3.2
  shared_preferences: ^2.2.0
  path_provider: ^2.1.0
  carousel_slider: ^4.2.1



  #signin
  google_sign_in: ^6.0.2
  sign_in_with_apple: ^4.3.0

  #firebase
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.1

#flutter_native_splash:
#  background color: "#f8f4f5"
#  color: "#f8f4f5"
#  image: assets/images/launcher.png
#  android: true
#  ios: true
#  fullscreen: true
#  android_12:
#    image: assets/images/launcher.png
#    icon_background_color: "#f8f4f5"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo.png"


flutter:


  uses-material-design: true


  assets:
     - assets/images/
     - assets/icons/
     - assets/icons/mood/
     - assets/images/logo.png
     - assets/cities/cities.json

  fonts:
    - family: Abril Fatface
      fonts:
        - asset: assets/fonts/AbrilFatface-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
